package tc.bites;

import org.testng.Assert;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

/**
 *  Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 * Example:
 * Input:
 * s = "abcd"
 * t = "abcde"
 * Output:
 * e
 * Explanation:
 * 'e' is the letter that was added.
 */
public class FindTheDifferenceTest {
    @DataProvider(name="dataProvider")
    public static Object[][] dataProvider() {
        Object[][] cases = {
            {"foo", "foot", 't'},
            {"foo", "oxfo", 'x'},
            {"abcd", "ebcda", 'e'},
            {"foo", "ofoo", 'o'},
            {"abcd", "aabcd", 'a'},
        };
        return cases;
    }

    @Test(dataProvider="dataProvider")
    public static void testDifference(String s, String t, char e) {
        FindTheDifference f = new FindTheDifference();
        char a = f.findTheDifference(s, t);
        Assert.assertEquals(e, a);
    }
}
